HOST: http://api.ihelpoo.com/v1

--- IHELPOO API version 1.0 ---
---
Welcome to IHELPOO API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Mobile App JSON Api
The following is a section of resources related to the Android or iOS app
--
List the latest mobile app's version for being checked
GET /versions.json
< 200
< Content-Type: application/json; charset=UTF-8
{"update":{"wp7":"1.0","ios":"1.0.0","android":{"versionCode":"1","versionName":"1.0.1","downloadUrl":"http://www.ihelpoo.com/app/mobile/downloads/ihelpoo-1.0.1.apk","updateLog":"\r\n  版本信息：IHelpOO.com for Android v1.0.1\r\n  更新日志：首次发布\r\n"}}}

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }
